services:
  nemo-safety:
    # build:
    #   context: .
    #   dockerfile: deploy/Dockerfile
    image: gitlab-master.nvidia.com:5005/swdl-nemollm-mlops/nemo-safety:0528
    volumes:
      - ./notebooks:/notebooks
    command: jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "all" ]
              capabilities: [ gpu ]
